/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-04-28 at 01:29:09 UTC 
 * Modify at your own risk.
 */

package com.appspot.turnerrs_gourmade.gourmade.model;

import android.util.Log;

import edu.rosehulman.turnerrs.gourmate.Constants;

/**
 * Model definition for Step.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the gourmade. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Step extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("step_number")
  private java.lang.String stepNumber;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("step_text")
  private java.lang.String stepText;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStepNumber() {
    return stepNumber;
  }

  /**
   * @param stepNumber stepNumber or {@code null} for none
   */
  public Step setStepNumber(java.lang.String stepNumber) {
    this.stepNumber = stepNumber;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStepText() {
    return stepText;
  }

  /**
   * @param stepText stepText or {@code null} for none
   */
  public Step setStepText(java.lang.String stepText) {
    this.stepText = stepText;
    return this;
  }

  @Override
  public Step set(String fieldName, Object value) {
    return (Step) super.set(fieldName, value);
  }

  @Override
  public Step clone() {
    return (Step) super.clone();
  }

  public String[] toStringArray() {
    String[] s = {this.stepNumber, this.stepText};
    return s;
  }

  public Step(String[] array) {
    try {
      this.stepNumber = array[0];
      this.stepText = array[1];
    } catch (Exception e) {
      Log.e(Constants.LOG_NAME, "Invalid Step array: " + e);
    }
  }

  public Step() {

  }
}

